### ISSUE TITLE
ReCaptcha is not showing on comments pages

### ISSUE THREAD

**Issue by icemarkom** [mcguffin/wp-recaptcha-integration#12]
For a few releases at least, I had to manually enable recaptcha for comments. In the latest (1.0.4),  line 152 in wp-recaptcha-integration.php was commented out. Removing the comment seems to fix the issue every time, so I suppose it may be an oversight of troubleshooting.

add_action('comment_form_after_fields',array($this,'print_recaptcha_html'),10,0);

**Comment by mcguffin** [comment]
You're right, I've changed the hook from action `comment_form_after_fields` (before comments field) to filter `comment_form_defaults` a few versions ago. Purpose was to make the captcha appear  before the submit button, where I think it is placed best. Looks very much like your Themes simply does not use the `comment_form_defaults` filter.

Putting this in your themes functions.php (or better in a mu-plugin) will fix the issue permanently:
```
function recaptcha_comments_init() {
	if ( class_exists( 'WP_reCaptcha' ) ) {
		$rec = WP_reCaptcha::instance();
		if ( $rec->is_required() )
			add_action( 'comment_form_after_fields' , array( $rec , 'print_recaptcha_html' ) , 10 , 0 );
	}
}
add_action('init','recaptcha_comments_init');
```

**Comment by icemarkom** [comment]
I'm using a fairly vanilla version of zBench (only minor CSS tweaks as a
customization), so I'm probably not the only with this problem. Thanks for
the response anyways.

**Comment by mcguffin** [comment]
Update: efdad6622390ab69f1a254a3e21b43f2c2c9d62e introduced some action hooks for custom forms. See [Wiki page](https://github.com/mcguffin/wp-recaptcha-integration/wiki/Custom-Themes-and-Forms) for details.
