### ISSUE TITLE
ERROR: Invalid domain for site key

### ISSUE THREAD

**Issue by Graf007** [mcguffin/wp-recaptcha-integration#17]
It stopped working on my site.  How do I disable this to get into the site to put in another set of keys?

**Comment by mcguffin** [comment]
You either need access to the database or to the filesystem (FTP).

Shortest way would be to update the keys directly in the database. 
SQL:

    UPDATE wp_options SET option_value='NEW_PUBLIC_KEY' WHERE option_name='recaptcha_publickey;'
    UPDATE wp_options SET option_value='NEW_PRIVATE_KEY' WHERE option_name='recaptcha_privatekey;'

(`wp_options` may have a different prefix than `wp_`. The one you entered during installation).

With FTP access: edit your themes functions.php adding the following lines in PHP:

    update_option('recaptcha_publickey','NEW_PUBLIC_KEY');
    update_option('recaptcha_privatekey','NEW_PRIVATE_KEY');

**Comment by mcguffin** [comment]
Update: As of 04d0f2eaa2cfb8f541cbe2f07ff12fbd3c337e78 the plugin will let you log in when a) you are an administrator and b) one of the keys is invalid.
