### ISSUE TITLE
How to show reCaptcha / noCaptcha to custom comments template?

### ISSUE THREAD

**Issue by ChaosPower** [mcguffin/wp-recaptcha-integration#18]
Was wondering how to implement the plugin at a custom comments template?

**Comment by mcguffin** [comment]
It hooks into the WP filter `comment_form_defaults` (see https://developer.wordpress.org/reference/hooks/comment_form_defaults/), appending the captcha html to the `comment_notes_after` element. Here's the source:
https://github.com/mcguffin/wp-recaptcha-integration/blob/master/wp-recaptcha-integration.php#L318
So, just do what WordPress does ,and you should be fine.

**Comment by ChaosPower** [comment]
Hi mcguffin,

Thanks a lot for the fast reply. I found a different way, but will check out your suggestion.

Here is what I did.

    <?php WP_reCaptcha::instance()->print_recaptcha_html(); ?>

I am using roots theme and they have custom comments form. Your plugin is working however, it could not load to theirs. It looks like they remade the entire comments form's html from the start.

**Comment by mcguffin** [comment]
Hi ChaosPower, 
yeah sure, you can always print out the captcha HTML directly, but this would break the connection to the plugin setting. Also the "disable for known users" feature will not work properly and in the worst case an orphaned recaptcha DIV will mess up your DOM.

In order to cover a use case like yours, I just merged a slight change in plugin (yet untested) introducing some action listeneners that print out the HTML. Would you like to try `<?php do_action( 'print_comments_recaptcha' ) ?>`, and tell me if it works for you?

**Comment by ChaosPower** [comment]
Will try this one out.

Thanks a lot @mcguffin

**Comment by ChaosPower** [comment]
Hi,

do_action did not work.

here is my code

    <form action="<?php echo get_option( 'siteurl' ); ?>/wp-comments-post.php" method="post" id="commentform">
      <?php if ( is_user_logged_in() ) : ?>
        <p>
          <?php printf( __( 'Logged in as <a href="%s/wp-admin/profile.php">%s</a>.', 'shoestrap' ), get_option( 'siteurl' ), $user_identity ); ?>
          <a href="<?php echo wp_logout_url( get_permalink() ); ?>" title="<?php __( 'Log out of this account', 'shoestrap' ); ?>"><?php _e( 'Log out &raquo;', 'shoestrap' ); ?></a>
        </p>
      <?php else : ?>
        <label for="author"><?php _e( 'Name', 'shoestrap' ); if ( $req ) _e( ' (required)', 'shoestrap' ); ?></label>
        <input type="text" class="text" name="author" id="author" value="<?php echo esc_attr( $comment_author ); ?>" size="22" <?php if ( $req ) echo 'aria-required="true"'; ?>>
        <label for="email"><?php _e( 'Email (will not be published)', 'shoestrap' ); if ( $req ) _e( ' (required)', 'shoestrap' ); ?></label>
        <input type="email" class="text" name="email" id="email" value="<?php echo esc_attr( $comment_author_email ); ?>" size="22" <?php if ( $req ) echo 'aria-required="true"'; ?>>
        <label for="url"><?php _e( 'Website', 'shoestrap' ); ?></label>
        <input type="url" class="text" name="url" id="url" value="<?php echo esc_attr( $comment_author_url ); ?>" size="22">
      <?php endif; ?>
      <label for="comment"><?php _e( 'Comment', 'shoestrap' ); ?></label>
      <textarea name="comment" id="comment" class="input-xlarge" rows="5" aria-required="true"></textarea>
    <?php do_action( 'print_comments_recaptcha' ) ?>
      <p><input name="submit" class="btn btn-primary" type="submit" id="submit" value="<?php _e( 'Submit Comment', 'shoestrap' ); ?>"></p>
      <?php comment_id_fields(); ?>
      <?php do_action( 'comment_form', $post->ID ); ?>
    </form>

**Comment by ChaosPower** [comment]
Hi,

do_action did not work.

Below are 

    <form action="<?php echo get_option( 'siteurl' ); ?>/wp-comments-post.php" method="post" id="commentform">
      <?php if ( is_user_logged_in() ) : ?>
        <p>
          <?php printf( __( 'Logged in as <a href="%s/wp-admin/profile.php">%s</a>.', 'shoestrap' ), get_option( 'siteurl' ), $user_identity ); ?>
          <a href="<?php echo wp_logout_url( get_permalink() ); ?>" title="<?php __( 'Log out of this account', 'shoestrap' ); ?>"><?php _e( 'Log out &raquo;', 'shoestrap' ); ?></a>
        </p>
      <?php else : ?>
        <label for="author"><?php _e( 'Name', 'shoestrap' ); if ( $req ) _e( ' (required)', 'shoestrap' ); ?></label>
        <input type="text" class="text" name="author" id="author" value="<?php echo esc_attr( $comment_author ); ?>" size="22" <?php if ( $req ) echo 'aria-required="true"'; ?>>
        <label for="email"><?php _e( 'Email (will not be published)', 'shoestrap' ); if ( $req ) _e( ' (required)', 'shoestrap' ); ?></label>
        <input type="email" class="text" name="email" id="email" value="<?php echo esc_attr( $comment_author_email ); ?>" size="22" <?php if ( $req ) echo 'aria-required="true"'; ?>>
        <label for="url"><?php _e( 'Website', 'shoestrap' ); ?></label>
        <input type="url" class="text" name="url" id="url" value="<?php echo esc_attr( $comment_author_url ); ?>" size="22">
      <?php endif; ?>
      <label for="comment"><?php _e( 'Comment', 'shoestrap' ); ?></label>
      <textarea name="comment" id="comment" class="input-xlarge" rows="5" aria-required="true"></textarea>
    <?php do_action( 'print_comments_recaptcha' ) ?>
      <p><input name="submit" class="btn btn-primary" type="submit" id="submit" value="<?php _e( 'Submit Comment', 'shoestrap' ); ?>"></p>
      <?php comment_id_fields(); ?>
      <?php do_action( 'comment_form', $post->ID ); ?>
    </form>

**Comment by mcguffin** [comment]
Hmm. Logged out? Plugin activated for comments? Downloaded and installed latest version form github?

**Comment by ChaosPower** [comment]
@mcguffin I have the latest version from github. The plugin is active for comments, just not showing captcha part before the submit button. Probably because it's a custom form and not using comments_form()

**Comment by mcguffin** [comment]
Can you see a `<div class="g-recaptcha" ... />` in the output HTML? If yes then the hook works, and the problem is somewhere else. Besides others, there should be a `<script src="https://www.google.com/recaptcha/api.js?..." ... />` in the the footer. If also yes: can you see any javascript error in the console?

**Comment by ChaosPower** [comment]
@mcguffin yep it is there. It's only when comments_form() is not called. The form itself was made via php html. Please see

https://github.com/shoestrap/shoestrap-3/blob/master/templates/comments.php

Regards

**Comment by Tekuzo** [comment]
I am experiencing the same issue or a similar one. When I call do_action( 'print_comments_recaptcha'); all comment submissions fail on my customer comment form.

**Comment by mcguffin** [comment]
@Tekuzo Where do you call `do_action( 'print_comments_recaptcha');` It should be called right before the comment form submit button, if you desire to display a recaptcha there. Take a look here for a working example: https://gist.github.com/mcguffin/c0382448518a2b68e94a#file-comment-form-php-L25

**Comment by Tekuzo** [comment]
I was following the example of the wordpress comment form from the wordpress codex so my form looks like this.


		$args = array(
			'id_form'           => 'commentform',
			'id_submit'         => 'submit',
			'title_reply'       => __( 'Leave a Reply' ),
			'title_reply_to'    => __( 'Leave a Reply to %s' ),
			'cancel_reply_link' => __( 'Cancel Reply' ),
			'label_submit'      => __( 'Post Comment' ),

			'comment_field' =>  '<div class="row"><div class="form-group col-xs-12 col-sm-12 col-md-6">'.
			'<textarea placeholder="Comment" id="comment" name="comment" rows="8" aria-required="true" class="form-control">' .
			'</textarea></div></div>',

		  'must_log_in' => '<p class="must-log-in">' .
			sprintf(
			  __( 'You must be <a href="%s">logged in</a> to post a comment.' ),
			  wp_login_url( apply_filters( 'the_permalink', get_permalink() ) )
			) . '</p>',

		  'logged_in_as' => '<p class="logged-in-as">' .
			sprintf(
			__( 'Logged in as <a href="%1$s">%2$s</a>. <a href="%3$s" title="Log out of this account">Log out?</a>' ),
			  admin_url( 'profile.php' ),
			  $user_identity,
			  wp_logout_url( apply_filters( 'the_permalink', get_permalink( ) ) )
			) . '</p>',

		  'comment_notes_before' => '<p>' .
			__( 'Your email address will not be published.' ) . ( $req ? $required_text : '' ) .
			'</p>',

		  'comment_notes_after' => '<p>' .
			sprintf(
				__( 'You may use <abbr title="HyperText Markup Language">HTML</abbr> tags and attributes: %s' ),
				''
				) . '</p>'.
				'<div class="row"><div class="form-group col-xs-12 col-sm-6">'.
				'<input type="submit" class="btn btn-default" id="submit-new" value="' . __( 'Post Comment', 'textdomain' ) . '" />'.
				'</div></div>',

		  'fields' => apply_filters( 'comment_form_default_fields', array(

			'author' =>
				'<div class="row">'.
				'<div class="form-group col-md-6 col-sm-12">' .
				'<input class="form-control" placeholder="Name" id="author" name="author" type="text" value="' . esc_attr( $commenter['comment_author'] ) .
				'" size="30"' . $aria_req . ' /></div></div>',

			'email' =>
				'<div class="row">'.
				'<div class="form-group col-md-6 col-sm-12 col-xs-12">'.
				'<input class="form-control" placeholder="Email" id="email" name="email" type="text" value="' . esc_attr(  $commenter['comment_author_email'] ) .
				'" size="30"' . $aria_req . ' /></div></div>',

			'url' =>
				'<div class="row">'.
				'<div class="form-group col-md-6 col-sm-12 col-xs-12">'.
				'<input class="form-control" placeholder="Website" id="url" name="url" type="text" value="' . esc_attr( $commenter['comment_author_url'] ) .
				'" size="30" /></div></div>'
			)
		  ),
		);
		comment_form($args);

**Comment by mcguffin** [comment]
Ah, I see you added the submit button to `$args['comment_notes_after']`. Thats where the plugin normally appends the captcha HTML. That one should work:

    $args = array(
        'id_form'           => 'commentform',
        'id_submit'         => 'submit',
        'title_reply'       => __( 'Leave a Reply' ),
        'title_reply_to'    => __( 'Leave a Reply to %s' ),
        'cancel_reply_link' => __( 'Cancel Reply' ),
        'label_submit'      => __( 'Post Comment' ),

        'comment_field' =>  '<div class="row"><div class="form-group col-xs-12 col-sm-12 col-md-6">'.
        '<textarea placeholder="Comment" id="comment" name="comment" rows="8" aria-required="true" class="form-control">' .
        '</textarea></div></div>',

      'must_log_in' => '<p class="must-log-in">' .
        sprintf(
          __( 'You must be <a href="%s">logged in</a> to post a comment.' ),
          wp_login_url( apply_filters( 'the_permalink', get_permalink() ) )
        ) . '</p>',

      'logged_in_as' => '<p class="logged-in-as">' .
        sprintf(
        __( 'Logged in as <a href="%1$s">%2$s</a>. <a href="%3$s" title="Log out of this account">Log out?</a>' ),
          admin_url( 'profile.php' ),
          $user_identity,
          wp_logout_url( apply_filters( 'the_permalink', get_permalink( ) ) )
        ) . '</p>',

      'comment_notes_before' => '<p>' .
        __( 'Your email address will not be published.' ) . ( $req ? $required_text : '' ) .
        '</p>',

      'comment_notes_after' => '<p>' .
        sprintf(
            __( 'You may use <abbr title="HyperText Markup Language">HTML</abbr> tags and attributes: %s' ),
            ''
            ) . '</p>',

      'fields' => apply_filters( 'comment_form_default_fields', array(

        'author' =>
            '<div class="row">'.
            '<div class="form-group col-md-6 col-sm-12">' .
            '<input class="form-control" placeholder="Name" id="author" name="author" type="text" value="' . esc_attr( $commenter['comment_author'] ) .
            '" size="30"' . $aria_req . ' /></div></div>',

        'email' =>
            '<div class="row">'.
            '<div class="form-group col-md-6 col-sm-12 col-xs-12">'.
            '<input class="form-control" placeholder="Email" id="email" name="email" type="text" value="' . esc_attr(  $commenter['comment_author_email'] ) .
            '" size="30"' . $aria_req . ' /></div></div>',

        'url' =>
            '<div class="row">'.
            '<div class="form-group col-md-6 col-sm-12 col-xs-12">'.
            '<input class="form-control" placeholder="Website" id="url" name="url" type="text" value="' . esc_attr( $commenter['comment_author_url'] ) .
            '" size="30" /></div></div>'
        )
      ),
    );
    $args = apply_filters( 'comment_form_defaults' , $args );
    $args['comment_notes_after'] .= '<div class="row"><div class="form-group col-xs-12 col-sm-6">'.
            '<input type="submit" class="btn btn-default" id="submit-new" value="' . __( 'Post Comment', 'textdomain' ) . '" />'.
            '</div></div>';

    comment_form($args);

**Comment by Tekuzo** [comment]
That worked perfectly. Thank you for the help.
