### ISSUE TITLE
Theme Hook

### ISSUE THREAD

**Issue by adamdehaven** [mcguffin/wp-recaptcha-integration#23]
Within WordPress I'd like to show the Dark theme on Pages, but I'd like to show the Light theme on Posts. I've been playing around with the plugin, but is there a way to insert a hook into my `functions.php` file in order to switch the theme?

**Comment by mcguffin** [comment]
You can give `pre_option_recaptcha_theme` a try. Possible return values for a noCaptcha are `light` and `dark`.

**Comment by adamdehaven** [comment]
@mcguffin - Any chance you could provide me with an example? I don't see that hook anywhere..?
