### ISSUE TITLE
wp-recaptcha-integration 1.1.3 doesn't work with ninjaforms

### ISSUE THREAD

**Issue by G3NSVRV** [mcguffin/wp-recaptcha-integration#24]
After update wordpress tells me it have an error trying activate wp-recaptcha-integration plugin. After that in ninja forms, nothing is working.

**Comment by mcguffin** [comment]
WP 4.1.1, NinjaForms 2.9.7 and recaptcha integration 1.1.3 are working well for me. 
What do you mean by "nothing is working"? A white screen of death?
What did the error message exactly say?

**Comment by G3NSVRV** [comment]
The plugin wp-recaptcha-integration-master/wp-recaptcha-integration.php has been deactivated due to an error: Plugin file does not exist.

**Comment by mcguffin** [comment]
> The plugin wp-recaptcha-integration-master/wp-recaptcha-integration.php has been deactivated due to an error: Plugin file does not exist.

Ah, I see: You initially installed the plugin from a github downloaded ZIP (the '-master' at the end of the plugin directory name tells me so), and then ran the update from the official WP plugin repository, which puts the plugin into a directory without '-master' at the end. Surely WP thinks it is gone, afterward.
Uninstalling and then reinstalling from the WP-Plugin repository will fix this once and for ever.

**Comment by G3NSVRV** [comment]
I've installed the plugin from zero and from the plugins admin in wordpress. The plugin works fine but I cannot put in ninjaforms (actually I can and show me I've puted in but it doens't work in the real page, just not showing).
