### ISSUE TITLE
Captcha Gone

### ISSUE THREAD

**Issue by johanguse** [mcguffin/wp-recaptcha-integration#28]
After submit without validating, captcha is gone.

![untitled-1](https://cloud.githubusercontent.com/assets/6184866/7377007/0e510134-edba-11e4-935a-296c0318095e.jpg)

**Comment by mcguffin** [comment]
Could be an Ajax issue.
Would you mind to try out this branch: https://github.com/mcguffin/wp-recaptcha-integration/tree/maybe-ajax-fix
