### ISSUE TITLE
No longer working on WP 4.2.2

### ISSUE THREAD

**Issue by stopspazzing** [mcguffin/wp-recaptcha-integration#31]
I have tested this on multiple sites I used with different themes, doesnt seem to work on WP 4.2.2, which all of them use. Used to work fine on login pages and contact form 7. Guessing since new WP update? Please fix.

**Comment by stopspazzing** [comment]
Odd for some odd reason now only showing up on anything WP but NOT showing up on CF7. Seems it may just be an issue with CF7 1.4.2

**Comment by ZoolWay** [comment]
Got the same problem, ReCaptcha shows in comments but not in CF7.

**Comment by stopspazzing** [comment]
Shows up fine on my login page; I have tested other recaptcha plugins that support CF7, all of them are broken for CF7. This must have been an update that broke everything.

**Comment by mcguffin** [comment]
I just tried it with a blank WordPress 4.2.2, CF7 1.4.2 and ReCaptcha Integration 1.1.5. Worked well...
Can you see any JavaScript errors?

**Comment by stopspazzing** [comment]
ODD, now is starting to work. IDK what happened. Thank you for checking.
