### ISSUE TITLE
recaptcha inside shortcode

### ISSUE THREAD

**Issue by beherit** [mcguffin/wp-recaptcha-integration#34]
I writing plugin where I return form inside shortcode (add_shortcode). I want to add captcha but I have problem - do_action('recaptcha_print') is printing captcha outside the shortcode. The question is - how to return recaptcha code without echo?

**Comment by mcguffin** [comment]
`$captcha_html = apply_filters('recaptcha_html','');`
Here's some more to read: https://github.com/mcguffin/wp-recaptcha-integration#filter-featurerecaptcha_html

**Comment by beherit** [comment]
Thank You :)
