### ISSUE TITLE
Check if valid with jQuery/Ajax?

### ISSUE THREAD

**Issue by adamdehaven** [mcguffin/wp-recaptcha-integration#37]
I've looked through the documentation but can't seem to find an answer for what I'm trying to do...

I'm using a 4.2.2-compliant comment form. On form submit, I'd like to check if the reCaptcha is valid or not in order to then process the form (Basically, I'd like to validate the form and reCaptcha on the page in order to show an error before submitting the form, instead of showing the Wordpress error on a new page as shown below)
![screen shot 2015-06-12 at 12 01 34 pm](https://cloud.githubusercontent.com/assets/2229946/8134134/cafd2d68-10fa-11e5-9169-1f7a236c543f.png)

I have an ajax call in my form submit handler, but how can I check if the reCaptcha is valid?
```js
jq.ajax({
    type: 'POST',
    url: 'path/to/something/if/needed.php',
    dataType:'text',
    success: function(result){
        if (result === true) {
            // ... process form
        } else {
            // ... show error
        }
    }
 });
```

**Comment by mcguffin** [comment]
Sadly there is no easy way to safely validate a recaptcha form element client side. Validation happens by sending the users response to the google recaptcha api, which will check if it matches the captcha challenge. As you will have to send the secret key along with the users response, it is definitely a bad idea to do this in JavaScript.
You can use the JS API method `grecaptcha.getResponse` to check if the user gave a response. (See https://developers.google.com/recaptcha/docs/display#js_api for details)

Example:

    var widget_id = jq('#g-recaptcha-0').data('widget-id');
    if ( grecaptcha.getResponse( widget_id ) !== "" ) {
        // user possibly solved captcha
    } else {
        // put error
    }

The `widget_id` variable in the script above must match the captcha instance on the page. You can find it in the `data-widget-id` attribute at the recaptcha div.

Please note, that having a response does not necessarily mean that the user really solved the captcha. It could be some crazy garbage injected by a bot also. For security you **must** verify the captcha server side, before you insert the comment. (https://github.com/mcguffin/wp-recaptcha-integration/wiki/Custom-Themes-and-Forms#validating-1)
