### ISSUE TITLE
Unable to insert Captcha element in CF7

### ISSUE THREAD

**Issue by yiip87** [mcguffin/wp-recaptcha-integration#38]
Steps to reproduce:

1. Create or edit a contact form in CF7
2. Click the `reCAPTCHA` button in the form editor
3. The popup opens as expected, but there is no content

I think this line may be the culprit:

https://github.com/mcguffin/wp-recaptcha-integration/blob/master/inc/class-wp_recaptcha_contactform7.php#L99

I was able to insert a reCAPTCHA element by removing the `hidden` class with the Firefox devtools.

Software:
- Wordpress 4.2.2
- WP reCaptcha Integration 1.1.6

**Comment by mcguffin** [comment]
Thanks for letting me know!
CF7 4.2 introduced a new UI concept with a completely different way how tags generated and inserted. Removing the hidden class wouldn't be enough. I'm currently working on a rebuild of the tag generation part...

**Comment by yiip87** [comment]
Works like a charm. Thanks for the quick fix! :rocket:
