### ISSUE TITLE
Czech localization not working

### ISSUE THREAD

**Issue by MikkCZ** [mcguffin/wp-recaptcha-integration#79]
After update to the latest version I have noticed in the notes, that the plugin has been recently localized to Czech by @frantisekz. Unfortunately the UI of the plugin is not localized - I still see everything in English on several instances where I use it.

**Comment by MikkCZ** [comment]
@frantisekz @mcguffin May I help with this somehow?

**Comment by frantisekz** [comment]
@MikkCZ The translation is probably outdated, but I am not 100% sure...

**Comment by MikkCZ** [comment]
Closing. I am not using the plugin anymore, and cannot tell whether this is still the case or not. Feel free to reopen or file a new issue, if there are still some troubles with Czech l10n and you want to let the developers know.
